#pragma once

#include <nlohmann/json.hpp>

#include <cstdint>
#include <string>
#include <vector>

// The wire contracts of the pipeline, in one place.
//
// These structs are shared rather than duplicated per service on purpose: a
// queue is a contract between exactly two services, and keeping two private
// copies of it is how the producer and the consumer silently drift apart.
// Serialisation is generated by NLOHMANN_DEFINE_TYPE_INTRUSIVE — it is strict,
// so a message missing a field throws on parse instead of being silently read
// as a default. Consumers catch that and reject the message.

namespace habr::shared::messaging {

// Queue names, so a typo is a link error rather than a message that vanishes
// into a queue nobody reads.
inline constexpr const char* kRawArticlesQueue = "raw_articles";
inline constexpr const char* kParsedArticlesQueue = "parsed_articles";

// digest_ready is a fanout exchange, not a plain queue.
//
// A queue hands each message to exactly one of its consumers, so as soon as a
// second subscriber appeared (the web UI), notifier and web would have started
// splitting digests between them — half written to a file, half shown on the
// page, neither of them wrong-looking enough to notice. Every subscriber binds
// its own durable queue to the exchange instead, and each gets every digest.
//
// The two upstream hops keep using plain queues on the default exchange: they
// have exactly one consumer each, and there competing consumers would be a
// feature (scale the parser out), not a bug.
inline constexpr const char* kDigestReadyExchange = "digest_ready";
inline constexpr const char* kDigestNotifierQueue = "digest_ready.notifier";
inline constexpr const char* kDigestWebQueue = "digest_ready.web";

// ---------------------------------------------------------------------------
// raw_articles: Fetcher -> Parser
// ---------------------------------------------------------------------------

struct RawArticlesMessage {
    // Timestamp of the moment the HTTP request started. A UUID would be
    // overkill at one request per interval, and a timestamp is greppable.
    std::string fetch_id;
    std::string source_url;
    std::string raw_html;
    std::string fetched_at;
    // Generated once per "fetch -> parse -> store -> digest" cycle and copied
    // downstream unchanged.
    std::string trace_id;

    NLOHMANN_DEFINE_TYPE_INTRUSIVE(RawArticlesMessage, fetch_id, source_url, raw_html, fetched_at,
                                   trace_id)
};

// ---------------------------------------------------------------------------
// parsed_articles: Parser -> Storage
// ---------------------------------------------------------------------------

struct ParsedArticle {
    // Habr's own numeric article id, taken from <article id="...">. It is the
    // deduplication key for Storage.
    std::string article_id;
    std::string url;
    std::string title;
    std::string author;
    std::string published_at;
    std::vector<std::string> hubs;
    std::string complexity;
    std::string reading_time;
    // Rating, i.e. upvotes minus downvotes; can legitimately be negative.
    int64_t votes = 0;
    int64_t views = 0;
    int64_t bookmarks = 0;
    int64_t comments = 0;

    NLOHMANN_DEFINE_TYPE_INTRUSIVE(ParsedArticle, article_id, url, title, author, published_at,
                                   hubs, complexity, reading_time, votes, views, bookmarks,
                                   comments)
};

struct ParsedArticlesMessage {
    std::string fetch_id;
    std::string source_url;
    std::string parsed_at;
    std::string trace_id;
    // One message per fetched page rather than one per article: the whole page
    // is a single point-in-time snapshot, and splitting it would make the
    // trace_id span N messages for no gain at this scale.
    std::vector<ParsedArticle> articles;

    NLOHMANN_DEFINE_TYPE_INTRUSIVE(ParsedArticlesMessage, fetch_id, source_url, parsed_at, trace_id,
                                   articles)
};

// ---------------------------------------------------------------------------
// digest_ready: Storage -> Notifier
// ---------------------------------------------------------------------------

struct DigestArticle {
    std::string article_id;
    std::string url;
    std::string title;
    std::string author;
    std::string published_at;
    std::vector<std::string> hubs;
    int64_t votes = 0;
    int64_t views = 0;
    int64_t bookmarks = 0;
    int64_t comments = 0;
    // Weighted ranking score computed by Storage; see storage/src/article_store.cpp.
    double score = 0.0;
    // trace_id of the fetch that last updated this article. A digest aggregates
    // many fetch cycles, so it cannot inherit a single upstream trace_id — it
    // carries its own (below) and preserves the per-article one here.
    std::string source_trace_id;

    NLOHMANN_DEFINE_TYPE_INTRUSIVE(DigestArticle, article_id, url, title, author, published_at,
                                   hubs, votes, views, bookmarks, comments, score, source_trace_id)
};

struct DigestReadyMessage {
    std::string digest_id;
    std::string generated_at;
    std::string trace_id;
    // How far back the ranking window reached, in hours.
    uint32_t period_hours = 24;
    std::vector<DigestArticle> articles;

    NLOHMANN_DEFINE_TYPE_INTRUSIVE(DigestReadyMessage, digest_id, generated_at, trace_id,
                                   period_hours, articles)
};

} // namespace habr::shared::messaging
